"""empty message

Revision ID: 268230243cc3
Revises: 
Create Date: 2025-05-30 03:54:56.263834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268230243cc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
